name: MediaWarp Binary Builder

on:
  workflow_call:
    inputs:
      APP_VERSION:
        description: '用于二进制可执行文件的文件名'
        required: true
        type: string

env:
  APP_VERSION: ${{ github.event.inputs.APP_VERSION }}
  APP_NAME: MediaWarp
  BINARY_DIR: bin

jobs:
  binary-builder:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          os: [linux, windows, darwin]
          arch: [amd64, arm64]
          
      steps:
        - name: Clone Repository
          uses: actions/checkout@v4

        - name: Set Up Golong Environment
          uses: actions/setup-go@v5
          with:
            go-version: "1.22.5"

        - name: Build Binary for ${{ matrix.os }}-${{ matrix.arch }}
          run: |
            GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o ${{ env.BINARY_DIR }}/${{ env.APP_NAME }}-v${{ env.APP_VERSION }}-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.os == 'windows' && '.exe' || '' }}

        - name: Upload Binary
          uses: actions/upload-artifact@v4
          with:
            name: ${{ env.APP_NAME }}-v${{ env.APP_VERSION }}-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.os == 'windows' && '.exe' || '' }}
            path: ${{ env.BINARY_DIR }}

