name: MediaWarp Release

on:
  push:
    branches:
      - main
    paths:
      - core/version.go

env:
  APP_NAME: MediaWarp
  APP_VERSION: "0.0.0"

jobs:
  get-version:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: APP Version
        run: |
          echo "APP_VERSION=$(cat core/version.go | sed -ne 's/const\sAPP_VERSION\sstring\s=\s"v\(.*\)"/\1/gp')" >> $GITHUB_ENV
          echo "检测到版本号为 $APP_VERSION"

  docker-builder:
    name: Docker Image Builder
    needs: get-version
    uses: ./.github/workflows/docker-builder.yaml
    with:
      APP_VERSION: ${{ env.APP_VERSION }}
      IS_LATEST: true

  binary-builder:
    name: Binary Image Builder
    needs: get-version
    uses: ./.github/workflows/binary-builder.yaml
    with:
      APP_VERSION: ${{ env.APP_VERSION }}

  create-release:
    permissions: write-all
    runs-on: ubuntu-latest
    needs: [ docker-builder, binary-builder ]
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.APP_NAME}}-v${{ env.APP_VERSION}}
          path: ${{ github.workspace }}/bin

      - name: Create Release
        uses: softprops/action-gh-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: v${{ env.APP_VERSION }}
          tag_name: v${{ env.APP_VERSION }}
          body: ${{ github.event.commits[0].message }}
          files: ${{ github.workspace }}/bin/*
          draft: false
          prerelease: false
